### ISSUE TITLE
Question about `inflationExceedsAllowance`

### ISSUE THREAD

**Issue by cymqqqq** [RGB-WG/rgb-interfaces#8]
In the `InflationAsset`, there is the `inflationExceedsAllowance` which describes: 
"you try to issue more assets than allowed by the contract terms", what does the `contract terms` mean? Should we change it to a detailed explanation?(Like "you try to issue more assets than allowed by the `inflation allowance`").

**Comment by dr-orlovsky** [comment]
Yes, inflation allowance is a part of contract terms and may be more easy to understand.
